- name: Cargo Test
  # You may pin to the exact commit or the version.
  # uses: Kristories/cargo-test@55a4112b486d64c66db881cdc80e7d66af5fe110
  uses: Kristories/cargo-test@v1.0.0
  with:
    # Path to Cargo.toml
    manifest-path: # optional
